---
fatsecret:
  oauth1:
    consumer_key: ${FATSECRET_CONSUMER_KEY}
    consumer_secret: ${FATSECRET_CONSUMER_SECRET}
  oauth2:
    client_id: ${FATSECRET_OAUTH_CLIENT_ID}
    client_secret: ${FATSECRET_OAUTH_CLIENT_SECRET}

telegram:
  admin_id: ${TELEGRAM_ADMIN_ID}
  bot_token: ${TELEGRAM_BOT_TOKEN}

user_backend:
  active: files
  files:
    name: "creds.yaml"
    user_isolation: false
